### ISSUE TITLE
This is nice, but I feel you should give some credit to plantuml

### ISSUE THREAD

**Issue by cameronsstone** [marcherdiego/json-visualizer#1]
I like what you've done here, and it saves me from putting my json into a plantuml file, but I feel you should give them some credit for the visualization, no?

**Comment by marcherdiego** [comment]
@cameronsstone you're right, I'll add that to the readme file and also to the release notes in the plugin itself.

**Comment by cameronsstone** [comment]
Thanks! And thanks for the plugin!
